version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo-local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: addressdb
    volumes:
      - mongo-data:/data/db

  address-service:
    build: .
    container_name: address-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/addressdb"

volumes:
  mongo-data:
